blank_issues_enabled: false
contact_links:
  - name: ❓ Ask a question
    url: https://github.com/vmware-labs/ml-conversational-analytic-tool/discussions
    about: Please post questions in discussions.
